version: '3.3'
services:
  configuration_server:
    image: training/configuration
    restart: on-failure
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    networks:
      cloud:
        ipv4_address: ${CONFIGURATION_SERVER}

  discovery_server:
    image: training/discovery
    restart: on-failure
    ports:
      - 8001:8080
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - PING_TIMEOUT=${PING_TIMEOUT}
      - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
      - DEFAULT_PORT=${DEFAULT_PORT}
    networks:
      cloud:
        ipv4_address: ${DISCOVERY_SERVER}

  gateway_server:
    image: training/gateway
    restart: on-failure
    ports:
      - 8000:8080
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - PING_TIMEOUT=${PING_TIMEOUT}
      - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
      - DEFAULT_PORT=${DEFAULT_PORT}
    networks:
      cloud:
        ipv4_address: ${GATEWAY_SERVER}

  users_database:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/users:/var/lib/postgresql/data/application
    networks:
      cloud:
        ipv4_address: ${USERS_DATABASE_SERVER}

  users_microservice:
    image: training/users
    restart: on-failure
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - PING_TIMEOUT=${PING_TIMEOUT}
      - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
      - DEFAULT_PORT=${DEFAULT_PORT}
      - DEFAULT_PROFILE=${DEFAULT_PROFILE}
    networks:
      cloud:

  departments_database:
    image: postgres:9.6.5-alpine
    environment:
      - POSTGRES_DB=departments
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ./data/departments:/var/lib/postgresql/data/application
    networks:
      cloud:
        ipv4_address: ${DEPARTMENTS_DATABASE_SERVER}

  departments_microservice:
    image: training/departments
    restart: on-failure
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - PING_TIMEOUT=${PING_TIMEOUT}
      - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
      - DEFAULT_PORT=${DEFAULT_PORT}
      - DEFAULT_PROFILE=${DEFAULT_PROFILE}
    networks:
      cloud:
        ipv4_address: ${CLIENT_SERVER}

  client:
    image: training/client
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      cloud:

  zipkin_server:
    image: training/zipkin
    restart: on-failure
    ports:
      - 8002:8080
    environment:
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - PING_TIMEOUT=${PING_TIMEOUT}
      - CONFIGURATION_SERVER_URI=${CONFIGURATION_SERVER_URI}
      - DEFAULT_PORT=${DEFAULT_PORT}
    networks:
      cloud:
        ipv4_address: ${ZIPKIN_SERVER}

  kafka_server:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=messages
      - ADVERTISED_HOST=localhost  # 192.168.0.17 for production
      - ADVERTISED_PORT=9092
    networks:
      cloud:
        ipv4_address: ${KAFKA_SERVER}

networks:
  cloud:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}